on:
  workflow_dispatch:

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package
